# Generated by Django 5.1.8 on 2025-05-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
    ]
