# Generated by Django 5.1.8 on 2025-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
