# Generated by Django 5.1.8 on 2025-04-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslent', '0002_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название картинки')),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newslent.news', verbose_name='Пост')),
            ],
        ),
    ]
