# Generated by Django 5.1.8 on 2025-04-02 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslent', '0003_postattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Приложение к посту', 'verbose_name_plural': 'Приложения к постам'},
        ),
        migrations.AddField(
            model_name='postattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to='posts/images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='newslent.news', verbose_name='Пост'),
        ),
    ]
